### PR TITLE
fix: avoid parsing undefined source location

### PR DESCRIPTION
**Pull request by meteorlxy**
Currently, setting `sourceLatitude` and `sourceLongitude` to `undefined` will make `sourceLatLng` to be `'NaN,NaN'`

### CODE REVIEW

**Review by tschoffelen — APPROVED** [review]
Ah, this is great! Mind fixing the linting error? Then we can get this merged right away!

**Comment by meteorlxy** [comment]
Oops sorry I didn't even install deps locally. Let me fix those errors

**Comment by meteorlxy** [comment]
@tschoffelen fixed. also updated to use `!=null` to check the existence

**Review by tschoffelen — APPROVED** [review]

**Comment by tschoffelen** [comment]
Thanks!

Released to NPM as `react-native-map-link@2.11.2`

**Pull request merged**
