### PR TITLE
fix: issue 228 - export core of lib for better composability

### PR DESCRIPTION
**Pull request by ChrisLFieldsII**
fix issue #228 by exporting core utilities for special use cases

### CODE REVIEW

**Comment by tschoffelen** [comment]
I wonder if we are exposing these directly to end user if we can make them a little easier to use. Ideally, you'd just call getAvailableApps() without params and it would give you a list. The whole `generatePrefixes` bit feels like it should be an internal detail.

So maybe rather than exposing these directly, we should expose a convenience function that has this signature?

```
async function getAvailableMapsApps(options)
```

**Comment by ChrisLFieldsII** [comment]
I 100% agree with this. It felt weird to me as well. I will try to fix this soon!

**Comment by ChrisLFieldsII** [comment]
Ok, tested in my personal app and looking good. Def makes for a much cleaner api! Good recommendation. Lmk if you think anything else needs fixing with this PR

**Comment by ChrisLFieldsII** [comment]
Closing this PR in favor of issue #232

**Pull request closed without merging**
