### PR TITLE
add getApps

### PR DESCRIPTION
**Pull request by CodingByJerez**
add method getApps

### CODE REVIEW

**Comment by tschoffelen** [comment]
Seems like there is some duplication here between this PR and #231. I quite like the idea of outputting the title and app in the function, so would be fine with merging this, but also don't want to dismiss the work by @ChrisLFieldsII (so let me know if you have any thoughts Chris!)

Only thing this PR would need to be merged is some added documentation in the README.

**Comment by CodingByJerez** [comment]
sorry i didn't see there was a Pull request, I fed on your library for one of my applications and I wanted to share my patch :)

**Comment by ChrisLFieldsII** [comment]
This is exactly what I was thinking with the cherry on top so I'm totally cool closing the PR I have open and rolling with this!

**Comment by tschoffelen** [comment]
Thanks both! A few linting errors it seems (most notably reference to missing function `checkNotSupportedApps`), once those are fixed we can merge.

Really excited about this!

**Comment by CodingByJerez** [comment]
I corrected :), excuse me 🙊🙈 
I'm really too used to typescript 💘

**Review by tschoffelen — APPROVED** [review]
LGTM - thanks!

**Comment by tschoffelen** [comment]
Thanks for your contribution!

Released to NPM as `react-native-map-link@2.10.0`

**Pull request merged**
