### PR TITLE
Add source coordinates feature

### LINKED ISSUE #10: When open google maps, the starting point address is not informed
Is that expected? Is it possible to have the FROM address too, and not only the destiny address?

### PR DESCRIPTION
**Pull request by djalmaaraujo**
This fixes #10 

This pr add support to specify the sourceLatitude and sourceLongitude. If they are set, the apps will receive the correspondent param to use as the source location, instead of using the current user location.

The reason I am adding this is because Google maps app is not selecting the user default location, for some reason.

All supported links generated by the library:

```bash
http://maps.apple.com/?saddr=-8.0378585%2C-34.8734846&daddr=-8.1089021%2C-34.8910003&q=Location
comgooglemaps://?api=1&ll=-8.1089021%2C-34.8910003&q=Location&saddr=-8.0378585%2C-34.8734846&daddr=-8.1089021%2C-34.8910003
citymapper://directions?endcoord=-8.1089021%2C-34.8910003&startcoord=-8.0378585%2C-34.8734846
uber://?action=setPickup&dropoff[latitude]=-8.1089021&dropoff[longitude]=-34.8910003&pickup[latitude]=-8.0378585&pickup[longitude]=-34.8734846
lyft://ridetype?id=lyft&destination[latitude]=-8.1089021&destination[longitude]=-34.8910003&pickup[latitude]=-8.0378585&pickup[longitude]=-34.8734846
transit://directions?to=-8.1089021%2C-34.8910003&from=-8.0378585%2C-34.8734846
yandexnavi://build_route_on_map?lat_to=-8.1089021&lon_to=-34.8910003&lat_from=-8.0378585&lon_from=-34.8734846
```

ps: I tried to add tests to this library but jest is giving me a hard time, so I tested manually.

Another thing I added to the repo is the `.editorconfig` to prevent bad alignment. Feel free to comment, suggest changes.

@tschoffelen can you take a look? :)

### CODE REVIEW

**Comment by tschoffelen** [comment]
Thanks for the effort! Could you add documentation for these new params to the README? Then I can merge this.

**Comment by djalmaaraujo** [comment]
@tschoffelen I guess you saw the readme? :)

**Comment by djalmaaraujo** [comment]
@tschoffelen can you generate a new release so we can npm install?

**Comment by tschoffelen** [comment]
Done! `react-native-map-link@1.1.0`

Thanks again.

**Pull request merged**
