### PR TITLE
V3.0.0 - Big Refactor, updated libraries, project converted to typescript, Popup refactored

### PR DESCRIPTION
**Pull request by Fabianurrutia**
Changes:
- Project converted to Typescript
- Updated tests to work correctly with typescript
- Updated jest and lint configuration
- Refactored the popup component separating responsibilities
- Updated example project for working correctly with the last version of react-native-map-link
- From the main function of index, I extracted logic to create new functions, allowing them to be tested in the future if necessary and removing direct responsibility from the parent function.

Break Changes:
- Removed use of react-native-modal to use modal directly provided by react

### CODE REVIEW

**Comment by tschoffelen** [comment]
This is really awesome @Fabianurrutia! Thanks for doing all this work, so cool!

Give me a few more days to look into this and give it a test, and then we can get it merged next week.

**Comment by tschoffelen** [comment]
This looks great - I have one question, that I couldn't really find the answer to online: don't we need to compile the Typescript before publishing to NPM to make it work in older RN projects?

It looks like the current version of metro might support Typescript bundling of node modules out of the box, but most RN packages I could find on Github include a [compilation step](https://github.com/react-native-maps/react-native-maps/blob/master/package.json#L14) before publishing to NPM, I think we might need to add that as well?

**Comment by Fabianurrutia** [comment]
Yes, you're correct. It's generally a good practice to compile TypeScript code before publishing to npm, especially if you want to ensure compatibility with older React Native projects or environments that might not support TypeScript natively.

I missed testing with previous versions, give me a couple of days and I'll do the update so it compiles correctly.

**Comment by tschoffelen** [comment]
Made one small change to the push workflow - going to merge this now, thanks for your amazing work on this!

**Review by tschoffelen — APPROVED** [review]

**Comment by meteorlxy** [comment]
> Also, I am wondering what the reason is for removing react-native-modal because the built-in one in RN is very barebones.

Agree with that. After upgrading to v3, the popup style was broken in our project. We need to build a new popup in our side.

**Comment by tschoffelen** [comment]
Yeah, that's a fair point. We can do more to fix the default styling here.

I'm happy with the move away from the separate `react-native-modal` dependency though, because only a small subset of the users of this library use the popup, so I want to keep the lib as lightweight as possible.

Happy to accept styling/UX improvement PRs for the popup though!

**Comment by andreialecu** [comment]
> I'm happy with the move away from the separate `react-native-modal` dependency though, because only a small subset of the users of this library use the popup, so I want to keep the lib as lightweight as possible.

Fwiw `react-native-modal` could be added as an optional peer dependency, so that users can choose whether to install it or not.

I'm not sure whether only a subset of users use the popup, though; the popup has been the main use of this library for us in several projects. As of now, we need to stick to v2. 

PS: The change could've been better documented as well. We only caught this after upgrading, and we had to revert.

**Comment by meteorlxy** [comment]
Yep. A detailed migration guide is necessary for a major version bump with such lots of breaking changes

**Pull request merged**
