### PR TITLE
Adding apps white list prop to Popup Component

### PR DESCRIPTION
**Pull request by gbahamondezc**
- Adding apps whitelist filtering in Popup Component
- Updating README with appsWhiteList property
- Adding intellij and vscode config folders to gitignore

#29

### CODE REVIEW

**Comment by tschoffelen** [comment]
Indeed, if this works on both the popup and the `askAppChoice` function, I'll happily merge this!

**Comment by gbahamondezc** [comment]
@tschoffelen

Sure, no problem, just a questions to clarify.

* @johanleroch  Both Popup mean in the **Popup** Component and in the **ActionSheet** which displays the **showLocation** function or im missing something?

**Comment by tschoffelen** [comment]
Yep, that is correct. This feature should also be available if you decide not to use the `<Popup>` component and instead use the `showLocation()` function (which in turn indeed produces a Actionsheet / Alert depending on the OS.

**Comment by gbahamondezc** [comment]
@tschoffelen  ok, make sense!

**Comment by gbahamondezc** [comment]
@tschoffelen @johanleroch 

As requested,  the prop `appsWhiteList` and same behavior as in the `Popup` Component was added to `showLocation` method (94d738a)

But, there's is a point that i want to discuss.

Currently, if someone pass a **misspelled** app name in the `appsWhiteList` property on `showLocation` options  or in  the `Popup Component` props

**Example:**
```js
showLocation({
      latitude: -33.419330,
      longitude: -70.608864,
      title: 'The White House',
      dialogTitle: 'This is the dialog Title',
      dialogMessage: 'This is the amazing dialog Message',
      cancelText: 'This is the cancel button text',
      appsWhiteList: ['gogle-maps'] // mispelled gogle instead of google
});
```

The behaviour is the following.

#### Popup Component
Popup shows an empty modal, since there's no apps matching with the `appsWhiteList`

screen shot 2018-06-09 at 5 57 42 pm

#### showLocation method
If there's just 1 app in the `appsWhiteList` and the app name is **misspelled**  nothing will happen because  [this code](https://github.com/includable/react-native-map-link/blob/823ebe669517c32c39d851c987a856b7d8a03784/utils.js#L59)  will leads to open the app but there's no apps since the app name is **misspelled** a not matches with any supported app.

#### The question
Should i perform some kind of validation on each element of `appWhiteList` prop in order to guarantee that there's no typo errors in app names? and if so, should it throws an exception? something like.

`'gogle-maps' not matches with any supported app, please provide a list of valid apps (apple-maps, google-maps, citymapper, uber, lyft, transit, waze, yandex, moovit) in appsWhiteList prop`

Or should we left this to the user and assume this behaviour as a normal consequence of the feature?

**Comment by johanleroch** [comment]
Hi @gbahamondezc,

First of all, nice work!
I think we should expose an enum containing all app names. That way they can import it and use it in the whitelist array without misspelling.

```
import { showLocation, APPS_ENUM } from 'react-native-map-link';

showLocation({
      latitude: -33.419330,
      longitude: -70.608864,
      title: 'The White House',
      dialogTitle: 'This is the dialog Title',
      dialogMessage: 'This is the amazing dialog Message',
      cancelText: 'This is the cancel button text',
      appsWhiteList: [APPS_ENUM.GOOGLE] // no mistake
});

```

On the other hand we can also display an empty message (on the showLocation method and Popup component) which explains there is nothing to show in the list and like you said an exception for no matching app names (in the case if the developer misspells).

What do you think about that ?

**Comment by tschoffelen** [comment]
Good ideas, but I don't think that necessary for this version. I'm happy to release this as-is, and add something like that later. 

I'm personally not a fan of using enum-like stuff in JS for this purpose, I would rather just show an exception like we already do for some other invalid option values: https://github.com/includable/react-native-map-link/blob/master/utils.js#L107

**Comment by gbahamondezc** [comment]
@johanleroch i agree in that a enum-like constant with the valid app names can be useful. 

But anyway it not solves the problem in this particular case, since the implementer still can just ignore the ENUM and use strings.

@tschoffelen just to understand, what's are the downsides for you of using enum-like stuff in JS?

Independent of the decision about  use or not enum-like stuff,  based in your opinions, i think  that a validation of the elements in the  `appsWhiteList` property throwing a exception if some element is not a valid app,  is necessary in both implementations.

@tschoffelen @johanleroch what do you think?

**Comment by tschoffelen** [comment]
It’s honestly more of a personal preference of mine, I just don’t like the way that style of code looks generally, especially considering that you’re only adding a layer of complexity (creating a constant that holds the exact value the title of the constant implies). Also, indeed, those can be easily ignored and replaced by their string versions, so why not use those in the first place?

Also, I’d like to keep the number of imports required to do something with this library to a minimum.

So string values with validation that throws a MapsException is definitely the way to go in my opinion.

**Comment by gbahamondezc** [comment]
@tschoffelen ok, it's a valid and interesting point of view,  thanks for the explanation.

@johanleroch you agree with the validation ?

**Comment by johanleroch** [comment]
@tschoffelen @gbahamondezc, yeah I agree with this point of view ;)

**Comment by gbahamondezc** [comment]
@tschoffelen @johanleroch  please review ;D!

**Comment by tschoffelen** [comment]
Released to NPM as `v2.0.4`.

**Pull request merged**
